#Functions of threading module

#1.current_thread(): It returns the current executing Thread object.

#2.getName() :IT returns the current executing thread name
#             Every thread in python has name,it may be the default name generated by python

import threading
import time

class x(threading.Thread):
    def run(self):
        time.sleep(10)     #Thread 2
        for p in range(10):
            print("Child Thread-1!!!")
            #print(threading.current_thread())
            print("Current Executing Thread:",threading.current_thread().getName())
            
class y(threading.Thread):
    def run(self):        #Thread 3
        time.sleep(15)
        for p in range(10):
            print("Child Thread-2!!!")
            #print(threading.current_thread())
            print("Current Executing Thread:",threading.current_thread().getName())
x1=x()          #MAin Thread
x1.start()
y1=y()
y1.start()
print(threading.current_thread())
print("Current Executing Thread:",threading.current_thread().getName())

for p in range(10):
    print("Main Thread!!!")













